# Comparing Performance Classification Cancer with SVM and Naive Bayes 

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import svm

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps,
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,

In [3]:
df = pd.read_csv ("D:/Code/Data/Data Cancer.csv")
df.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size  Bland Chromatin  \
0                  1                            2                3   
1                  5                            7                3   
2                  1                            2                3   
3                  1                            3                3   
4                  3                            2                3   

   Normal Nucleoli  Mitoses  Class  
0                1        1      2  
1                2        1      2  
2                1        1      2  
3                7        1      2  
4                1        1      2

In [6]:
LE=LabelEncoder()
df.Class=LE.fit_transform(df.Class)
df.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size  Bland Chromatin  \
0                  1                            2                3   
1                  5                            7                3   
2                  1                            2                3   
3                  1                            3                3   
4                  3                            2                3   

   Normal Nucleoli  Mitoses  Class  
0                1        1      0  
1                2        1      0  
2                1        1      0  
3                7        1      0  
4                1        1      0

In [7]:
df.tail()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
694                3                        1                         1   
695                2                        1                         1   
696                5                       10                        10   
697                4                        8                         6   
698                4                        8                         8   

     Marginal Adhesion  Single Epithelial Cell Size  Bland Chromatin  \
694                  1                            3                1   
695                  1                            2                1   
696                  3                            7                8   
697                  4                            3               10   
698                  5                            4               10   

     Normal Nucleoli  Mitoses  Class  
694                1        1      0  
695                1        1      0  
696               10        2      1  
697                6        1      1  
698                4        1      1

In [8]:
#Set 70% training and 30% testing
x=df.drop("Class",axis=1)
y=df.Class
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=123)

In [9]:
print(x_train)

     Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
34                 3                        1                         2   
33                 2                        1                         1   
285                8                       10                        10   
453                4                        5                         5   
295                5                        5                         7   
118                1                        1                         1   
15                 7                        4                         6   
42                 6                       10                        10   
514                6                        6                         7   
294                1                        1                         1   
171                1                        1                         1   
174                8                        6                         5   
227                8     

SVM Linear

In [10]:
#Linear Kernel
clf=svm.SVC(kernel='linear')

In [11]:
#Train the model using the training sets
clf.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
#Predict the response for the dataset
y_pred = clf.predict(x_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[127   4]
 [  3  76]]
             precision    recall  f1-score   support

          0       0.98      0.97      0.97       131
          1       0.95      0.96      0.96        79

avg / total       0.97      0.97      0.97       210



SVM Polinomial Berderajat 3

In [14]:
#Polynomial kernel
clfpoly = svm.SVC(kernel='poly', degree=3)

#Train the model using the training sets
clfpoly.fit(x_train, y_train)

#Predict the response for test dataset
y_predpoly = clfpoly.predict(x_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_predpoly))
print(classification_report(y_test,y_predpoly))

[[125   6]
 [  6  73]]
             precision    recall  f1-score   support

          0       0.95      0.95      0.95       131
          1       0.92      0.92      0.92        79

avg / total       0.94      0.94      0.94       210



Naive Bayes

In [16]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB(priors=None)

In [17]:
y_pred = clf.predict(x_test)

In [18]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[127   4]
 [  3  76]]
             precision    recall  f1-score   support

          0       0.98      0.97      0.97       131
          1       0.95      0.96      0.96        79

avg / total       0.97      0.97      0.97       210

